/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import UserInformation.AllUserInfo;
import UserInformation.UserInfo;
import UsersAndGroups.Group;
import UsersAndGroups.Leaf;
import UsersAndGroups.User;
import Visitor.CountVisitor;
import Visitor.TwitterVisitor;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import javax.swing.tree.TreeSelectionModel;

/**
 *
 * @author Andrew
 */
public class AdminFrame extends javax.swing.JFrame {
    public static AdminFrame adminFrame;
    private TwitterVisitor visitor;
    private AllUserInfo allUsers;
    private Group root;
    private DefaultTreeModel model;
    private int userCount;
    private int groupCount;
    private int messageCount;
    private int positiveCount;
    private UserInfo lastUpdatedUser;
    
    /**
     * Creates new form AdminFrame
     */
    private AdminFrame() {
        initComponents();
        allUsers = new AllUserInfo();
        userCount = 0;
        groupCount = 0;
        messageCount = 0;
        positiveCount = 0;
        visitor = new CountVisitor();
        setLocationRelativeTo(null);
        root = new Group("root");
        model = new DefaultTreeModel(root.getNode(), true);
        jTree.setModel(model);
        jTree.setVisible(true);
        
    }
    public AllUserInfo getAllUsers() {
        return allUsers;
    }
    //Store a record in map
    public void putInRecord (String key, UserInfo user) {
        allUsers.putUser(key, user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree = new javax.swing.JTree();
        jButtonAddUser = new javax.swing.JButton();
        jButtonAddGroup = new javax.swing.JButton();
        jButtonOpenUserView = new javax.swing.JButton();
        jButtonGetGroupTotal = new javax.swing.JButton();
        jButtonGetMessageTotal = new javax.swing.JButton();
        jButtonGetUsersTotal = new javax.swing.JButton();
        jButtonGetPositivePercent = new javax.swing.JButton();
        jTextFieldUserID = new javax.swing.JTextField();
        jTextFieldGroupID = new javax.swing.JTextField();
        jButtonCheckID = new javax.swing.JButton();
        jButtonGetLatest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jTree);

        jButtonAddUser.setText("Add User");
        jButtonAddUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddUserMouseClicked(evt);
            }
        });

        jButtonAddGroup.setText("Add Group");
        jButtonAddGroup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddGroupMouseClicked(evt);
            }
        });

        jButtonOpenUserView.setText("Open User View");
        jButtonOpenUserView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonOpenUserViewMouseClicked(evt);
            }
        });

        jButtonGetGroupTotal.setText("Total Groups");
        jButtonGetGroupTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGetGroupTotalMouseClicked(evt);
            }
        });
        jButtonGetGroupTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGetGroupTotalActionPerformed(evt);
            }
        });

        jButtonGetMessageTotal.setText("Total Messages");
        jButtonGetMessageTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGetMessageTotalMouseClicked(evt);
            }
        });

        jButtonGetUsersTotal.setText("Total Users");
        jButtonGetUsersTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGetUsersTotalMouseClicked(evt);
            }
        });

        jButtonGetPositivePercent.setText("Positive %");
        jButtonGetPositivePercent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGetPositivePercentMouseClicked(evt);
            }
        });

        jTextFieldUserID.setText("User ID");
        jTextFieldUserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserIDActionPerformed(evt);
            }
        });

        jTextFieldGroupID.setText("Group ID");

        jButtonCheckID.setText("Check Unique");
        jButtonCheckID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCheckIDMouseClicked(evt);
            }
        });

        jButtonGetLatest.setText("Get Latest Update");
        jButtonGetLatest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGetLatestMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldGroupID, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAddGroup, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAddUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonOpenUserView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonGetMessageTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonGetUsersTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonGetPositivePercent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCheckID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonGetGroupTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonGetLatest, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldGroupID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonOpenUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGetGroupTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGetUsersTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGetLatest, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGetMessageTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGetPositivePercent, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCheckID, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUserIDActionPerformed

    //Singleton get the admin frame object
    public static AdminFrame getAdminFrame() {
        if (adminFrame == null) {
            adminFrame = new AdminFrame();
        }
        return adminFrame;
    }
    
    //Set last updated user
    public void setLastUpdatedUser(UserInfo user) {
        lastUpdatedUser = user;
    }
    public UserInfo getLastUpdatedUser () {
        return lastUpdatedUser;
    }
    //On click listener will add user 
    private void jButtonAddUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddUserMouseClicked
        if (allUsers.getUsers().containsKey(jTextFieldUserID.getText())) {
            System.out.println("User already exists.");
            JOptionPane.showMessageDialog(this, "ERROR: User already exists.");
        }
        else {
            Leaf newUser = new User(jTextFieldUserID.getText());
            TreePath path = jTree.getSelectionModel().getSelectionPath();
            try {
               Leaf jTreeSelectedNode = new Group();
               jTreeSelectedNode.setNode((DefaultMutableTreeNode)path.getLastPathComponent());
               jTreeSelectedNode.add(newUser);
            }
            catch (Exception e) {
               root.add(newUser);
            }
            userCount++;
            allUsers.addUser(new UserInfo(jTextFieldUserID.getText()));
            model.reload(); 
        }
    }//GEN-LAST:event_jButtonAddUserMouseClicked
    //On click will add new group to jTree
    private void jButtonAddGroupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddGroupMouseClicked
        System.out.println("Added Group: " + jTextFieldGroupID.getText() + ".");
        Leaf newGroup = new Group(jTextFieldGroupID.getText());
        try {
            TreePath path = jTree.getSelectionModel().getSelectionPath();
            Leaf jTreeSelectedNode = new Group();
            jTreeSelectedNode.setNode((DefaultMutableTreeNode)path.getLastPathComponent());
            jTreeSelectedNode.add(newGroup);
        }
        catch (Exception e) {
            root.add(newGroup);
        }
        groupCount++;
        model.reload();
    }//GEN-LAST:event_jButtonAddGroupMouseClicked

    //Will open the selected user's information into a new frame
    private void jButtonOpenUserViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOpenUserViewMouseClicked
        try {
            TreePath path = jTree.getSelectionModel().getSelectionPath();
            Leaf jTreeSelectedNode = new Group();
            jTreeSelectedNode.setNode((DefaultMutableTreeNode)path.getLastPathComponent());
            UserInfo user = allUsers.getUserInfo(jTreeSelectedNode.getNode().toString());
            new UserViewFrame(user, allUsers);  
        }
        catch (Exception e){
            e.printStackTrace();
            System.out.println("Error: Please select a user");
        }
    }//GEN-LAST:event_jButtonOpenUserViewMouseClicked
    //Uses visitory pattern to visit users
    private void jButtonGetUsersTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGetUsersTotalMouseClicked
        JOptionPane.showMessageDialog(this, visitor.visitUsers());
    }//GEN-LAST:event_jButtonGetUsersTotalMouseClicked
     //Uses visitory pattern to visit groups
    private void jButtonGetGroupTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGetGroupTotalMouseClicked
        JOptionPane.showMessageDialog(this, visitor.visitGroups());
    }//GEN-LAST:event_jButtonGetGroupTotalMouseClicked
 //Uses visitory pattern to visit messages
    private void jButtonGetMessageTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGetMessageTotalMouseClicked
        JOptionPane.showMessageDialog(this, visitor.visitMessages());
    }//GEN-LAST:event_jButtonGetMessageTotalMouseClicked
    //Uses visitory pattern to visit positive messages
    private void jButtonGetPositivePercentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGetPositivePercentMouseClicked
        JOptionPane.showMessageDialog(this, visitor.visitPositives());
    }//GEN-LAST:event_jButtonGetPositivePercentMouseClicked

    private void jButtonGetGroupTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGetGroupTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGetGroupTotalActionPerformed

    private void jButtonCheckIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCheckIDMouseClicked
        if (visitor.checkID()) {
            JOptionPane.showMessageDialog(this, "All IDs are unique");
        }
        else {
            JOptionPane.showMessageDialog(this, "All IDs are NOT unique");
        }
    }//GEN-LAST:event_jButtonCheckIDMouseClicked

    private void jButtonGetLatestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGetLatestMouseClicked
        JOptionPane.showMessageDialog(this, this.getLastUpdatedUser().getID());
    }//GEN-LAST:event_jButtonGetLatestMouseClicked
    public void incrementMessage(){
        messageCount++;
    }
    public void incrementPositive() {
        positiveCount++;
    }
    public int getMessageCount() {
        return messageCount;
    }
    public int getUserCount() {
        return userCount;
    }
    public int getPositiveCount() {
        return positiveCount;
    }
    public int getGroupCount() {
        return groupCount;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddGroup;
    private javax.swing.JButton jButtonAddUser;
    private javax.swing.JButton jButtonCheckID;
    private javax.swing.JButton jButtonGetGroupTotal;
    private javax.swing.JButton jButtonGetLatest;
    private javax.swing.JButton jButtonGetMessageTotal;
    private javax.swing.JButton jButtonGetPositivePercent;
    private javax.swing.JButton jButtonGetUsersTotal;
    private javax.swing.JButton jButtonOpenUserView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldGroupID;
    private javax.swing.JTextField jTextFieldUserID;
    private javax.swing.JTree jTree;
    // End of variables declaration//GEN-END:variables
}
