/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import static UI.AdminFrame.getAdminFrame;
import UserInformation.AllUserInfo;
import UserInformation.Information;
import UserInformation.Tweet;
import UserInformation.UserInfo;
import UsersAndGroups.User;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;

/**
 *
 * @author Heather
 */
public class UserViewFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserViewFrame
     */
    private UserInfo user;
    private AllUserInfo allUsers;
    private DefaultListModel myWatchList;
    private DefaultListModel myNewsFeed;
    public UserViewFrame() {
        initComponents();
    }
    //Constructor using a user and also the map to all users
    public UserViewFrame(UserInfo user, AllUserInfo allInfo) {
        initComponents();
        allUsers = allInfo;
        this.user = user;
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        this.setVisible(true);
        myWatchList = new DefaultListModel(); 
        for (Information info : user.getWatchlist()) {
            myWatchList.addElement(info.getID());
        }
        jListCurrentFollowing =  new JList<>();
        jListCurrentFollowing.setModel(myWatchList);
        jListCurrentFollowing.setVisible(true);
        jScrollPaneCurrentFollowing.setViewportView(jListCurrentFollowing);
        
        
        myNewsFeed = new DefaultListModel();
        for (int i = user.getMessages().size() - 1; i >= 0; i--) {
            myNewsFeed.addElement(user.getMessages().get(i));
        }
        jListNewsFeed = new JList<>();
        jListNewsFeed.setModel(myNewsFeed);
        jListNewsFeed.setVisible(true);
        jScrollPaneNewsFeed.setViewportView(jListNewsFeed);
        
//        DefaultListModel test = (DefaultListModel) jListCurrentFollowing.getModel();
//        test.removeAllElements();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonFollowUser = new javax.swing.JButton();
        jTextFieldUserID = new javax.swing.JTextField();
        jScrollPaneCurrentFollowing = new javax.swing.JScrollPane();
        jListCurrentFollowing = new javax.swing.JList<>();
        jButtonTweet = new javax.swing.JButton();
        jTextFieldMessage = new javax.swing.JTextField();
        jScrollPaneNewsFeed = new javax.swing.JScrollPane();
        jListNewsFeed = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonFollowUser.setText("Follow");
        jButtonFollowUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFollowUserMouseClicked(evt);
            }
        });

        jTextFieldUserID.setToolTipText("User ID");

        jListCurrentFollowing.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneCurrentFollowing.setViewportView(jListCurrentFollowing);

        jButtonTweet.setText("Tweet");
        jButtonTweet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonTweetMouseClicked(evt);
            }
        });

        jTextFieldMessage.setToolTipText("[Insert Message Here]");

        jListNewsFeed.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneNewsFeed.setViewportView(jListNewsFeed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPaneCurrentFollowing, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextFieldUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonFollowUser, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonTweet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPaneNewsFeed))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFollowUser, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneCurrentFollowing, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTweet, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneNewsFeed, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Based on input text field will add users to the watch list
    private void jButtonFollowUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFollowUserMouseClicked
        String id = jTextFieldUserID.getText();
        AdminFrame adminFrame = getAdminFrame();
        try{
            UserInfo userToAdd = allUsers.getUserInfo(id);
            userToAdd.attach(user);
            user.getWatchlist().add(userToAdd);
            myWatchList.addElement(userToAdd.getID());
            adminFrame.getAllUsers().putUser(user.getID(), user);
        }
        catch (Exception e) {
            System.out.println("ID not found.");
        }
        
        
    }//GEN-LAST:event_jButtonFollowUserMouseClicked
    //Will add message to the list and also add it for followers of this person
    private void jButtonTweetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTweetMouseClicked
        String message = jTextFieldMessage.getText();
        if (message.contains("happy")) {
            getAdminFrame().incrementPositive();
        }
        getAdminFrame().incrementMessage();
        user.notifyObservers(message);
        user.getMessages().add(message);
        myNewsFeed.addElement(message);
        
        
    }//GEN-LAST:event_jButtonTweetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserViewFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFollowUser;
    private javax.swing.JButton jButtonTweet;
    private javax.swing.JList<String> jListCurrentFollowing;
    private javax.swing.JList<String> jListNewsFeed;
    private javax.swing.JScrollPane jScrollPaneCurrentFollowing;
    private javax.swing.JScrollPane jScrollPaneNewsFeed;
    private javax.swing.JTextField jTextFieldMessage;
    private javax.swing.JTextField jTextFieldUserID;
    // End of variables declaration//GEN-END:variables
}
